### ISSUE TITLE
Przygotowanie bazy danych

### ISSUE THREAD

**Issue by marcinlawnik** [akai-org/prawko_jazdy#2]
Przygotowanie jednego modelu wraz z jego obsługą w bazie sqlite przy użyciu jakiejś biblioteki typu ORM.

**Comment by Kossa123** [comment]
Jak dla mnie lepiej zrobić to przy użyciu odpowiednika Room'a z androida 

https://medium.com/@azozsahb99/room-database-equivalent-for-flutter-807c9729b58d
