### ISSUE TITLE
DrivenTime niezgodnosc nazwy z typem

### ISSUE THREAD

**Issue by kezc** [akai-org/prawko_jazdy#26]
trzeba sie zastanowic, bo jest pole:
lessonDuration
ono powinno być albo typu Duration
albo zostać DateTime tyle ze z nowa lessonEnd czy cos

**Comment by marcinlawnik** [comment]
Powinno być typy float, albo typu Duration jak go stworzycie.
Prościej jest pilnować czasu startu i czasu trwania niż dwóch timestampów.
